FROM python:3.12-slim

RUN python -m pip install --no-cache-dir --upgrade pip \
    && python -m pip install --no-cache-dir \
        matplotlib \
        numpy \
        pandas \
        scipy \
        seaborn

WORKDIR /workspace

